version: "2"

volumes:
  db_data: {}

services:

  frontend-app:
    build: /FrontEnd/.
    depends_on:
      - db
    ports:
      - 8090:8090
    expose:
      - 8090

  backend-app:
    build: /RetrospectiveTool/RetrospectiveTool/.
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080


  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: retrospectivetooldb
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql/data